name: Build and Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pages: write
      id-token: write

    steps:
      # 1. Checkout del repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Ejecutar action
      - name: Run Portfolio Generator
        uses: araceliponce-es/jinja2portfolio@main
        with:
          gh_token: ${{ secrets.GITHUB_TOKEN }}
          gh_username: ${{ github.actor }}

      # 3. Subir artefacto para GitHub Pages
      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      # 4. Deploy automático a GitHub Pages
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
