name: build and deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # usa yml en root de rama main de repo llamado jinja....
      - name: Run portfolio action
        uses: araceliponce-es/jinja2portfolio@main
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USERNAME: ${{ github.actor }}
